apiVersion: v1
kind: ConfigMap
metadata:
  name: branch-configmap-1
  namespace: default
  annotations:
    version: "v0.0.1"
  labels:
    razee/watch-resource: "lite"
data:
  key1: "1"
  key2: "2"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: branch-configmap-2
  namespace: default
  annotations:
    version: "v0.0.1"
  labels:
    razee/watch-resource: "lite"
data:
  key1: "1"
  key2: "2"
